modelfun <- function(Time, State, Pars){
currenttime<-unclass(as.POSIXct(strptime(date(),"%c")))[1] 
if(currenttime - Pars["starttime"]>=Pars["timeout"])
 stop("timeout!"); 
  with(as.list(c(State, Pars)), {
if(Time<12){
lag12_TcLymphnode<-0
}else{
lag12_TcLymphnode<- lagvalue(Time - 12,9)}
if(Time<24){
lag24_InfectedAPC<-0
}else{
lag24_InfectedAPC<- lagvalue(Time - 24,5)}
if(Time<48){
lag48_FreeInfluenza<-0
}else{
lag48_FreeInfluenza<- lagvalue(Time - 48,2)}
ReactionFlux1=K14*Epitheliumwithreplicatedinfluenza
ReactionFlux2=K16*Epitheliumwithreplicatedinfluenza
ReactionFlux3=K13*Epitheliumwithinfluenzaparticle
ReactionFlux4=K11*FreeInfluenza*EpitheliumLung
ReactionFlux5=K18*FreeInfluenza
ReactionFlux6=K48*FreeInfluenza*A
ReactionFlux7=K29*IL6
ReactionFlux8=K15*InfectedAPC+K49*Epitheliumwithreplicatedinfluenza
ReactionFlux14=K34*Epitheliumwithinfluenzaparticle*K40*lag12_TcLymphnode
ReactionFlux15=K34*Epitheliumwithreplicatedinfluenza*K40*lag12_TcLymphnode
ReactionFlux18=K27*ResistantEpithelium
ReactionFlux188=K288*IL6*ResistantEpithelium
ReactionFlux19=K24*K40*lag12_TcLymphnode+K47*Epitheliumwithreplicatedinfluenza+K57*InfectedAPC
ReactionFlux20=K26*IFNA1*EpitheliumLung
ReactionFlux200=K288*IL6*EpitheliumLung
ReactionFlux21=K25*IFNA1
ReactionFlux22=K28*IFNA1*Epitheliumwithreplicatedinfluenza
ReactionFlux222=K288*IL6*Epitheliumwithreplicatedinfluenza
ReactionFlux23=K28*IFNA1*Epitheliumwithinfluenzaparticle
ReactionFlux233=K288*IL6*Epitheliumwithinfluenzaparticle
ReactionFlux25=K37*lag24_InfectedAPC
ReactionFlux26=K32*ActivatedAPCLymphnode*Tnaive
ReactionFlux266=K322*(1E5-Tnaive)
ReactionFlux2666=K3222*FreeInfluenza*Tnaive
ReactionFlux27=K42*ActivatedAPCLymphnode
ReactionFlux29=K53*InfectedAPC
ReactionFlux32=0
ReactionFlux244=K45*TcLymphnode
ReactionFlux2444=K3222*FreeInfluenza*TcLymphnode
ReactionFlux66=K59*(1E5-A)
ReactionFlux88=K245*lag48_FreeInfluenza
ReactionFlux40=K400*8*2*TcLymphnode-K401*IgM
ReactionFlux50=K500*8*2*TcLymphnode-K501*IgG
ReactionFlux55=K555*FreeInfluenza*IgM+K556*FreeInfluenza*IgG
ReactionFlux1311=-Kp14*CR+Kp41*CRP
ReactionFlux1312=-KpC*CR
ReactionFlux1313=KCon/2
ReactionFlux1314=((1/(1+K1314/TP)))**Kn1
ReactionFlux1315=Km*(C_intracellularRDV_total*F_intracellular)
ReactionFlux1316=Kc*TP
ReactionFlux1317=Kcell*cell_number
ReactionFlux1318=Knew*C_intracellularRDV_total
ReactionFlux1319=CL_percell*(C_extracellularRDV_total*F_extracellular)/V_percell
ReactionFlux1320=CL_percell*(C_intracellularRDV_total*F_intracellular)/V_percell
ReactionFlux1321=((-Kp14*CR+Kp41*CRP)-KpC*CR+KCon/2)/V1
ReactionFlux9=Krenew*(4e8-EpitheliumLung-ResistantEpithelium-Epitheliumwithreplicatedinfluenza-Epitheliumwithinfluenzaparticle)

dEpitheliumwithreplicatedinfluenza=(-K14*Epitheliumwithreplicatedinfluenza+ReactionFlux1314*K13*Epitheliumwithinfluenzaparticle-(K34*Epitheliumwithreplicatedinfluenza*K40*lag12_TcLymphnode)-(K28*IFNA1*Epitheliumwithreplicatedinfluenza)-K288*IL6*Epitheliumwithreplicatedinfluenza)
dFreeInfluenza=(ReactionFlux2-K18*FreeInfluenza-(K555*FreeInfluenza*IgM+K556*FreeInfluenza*IgG))
dEpitheliumwithinfluenzaparticle=(-K13*Epitheliumwithinfluenzaparticle+K11*FreeInfluenza*EpitheliumLung-(K34*Epitheliumwithinfluenzaparticle*K40*lag12_TcLymphnode)-K28*IFNA1*Epitheliumwithinfluenzaparticle-K288*IL6*Epitheliumwithinfluenzaparticle)
dEpitheliumLung=(-K11*FreeInfluenza*EpitheliumLung+K27*ResistantEpithelium-K26*IFNA1*EpitheliumLung-K288*IL6*EpitheliumLung+Krenew*(4e8-EpitheliumLung-ResistantEpithelium-Epitheliumwithreplicatedinfluenza-Epitheliumwithinfluenzaparticle))
dInfectedAPC=(K48*FreeInfluenza*A-K53*InfectedAPC-0)
dIL6=(-K29*IL6+(K15*InfectedAPC+K49*Epitheliumwithreplicatedinfluenza)+K245*lag48_FreeInfluenza)
dResistantEpithelium=(-K27*ResistantEpithelium+K26*IFNA1*EpitheliumLung-K288*IL6*ResistantEpithelium)
dIFNA1=((K24*K40*lag12_TcLymphnode+K47*Epitheliumwithreplicatedinfluenza+K57*InfectedAPC)-K25*IFNA1)
dTcLymphnode=(-K45*TcLymphnode+K32*ActivatedAPCLymphnode*Tnaive-K3222*FreeInfluenza*TcLymphnode)
dActivatedAPCLymphnode=(K37*lag24_InfectedAPC-K42*ActivatedAPCLymphnode)
dA=K59*(1E5-A)-K48*FreeInfluenza*A
dEpiKilledbyIFN=(K28*IFNA1*Epitheliumwithreplicatedinfluenza)+K28*IFNA1*Epitheliumwithinfluenzaparticle
dEpiKilledbyIL6=K288*IL6*Epitheliumwithreplicatedinfluenza+K288*IL6*Epitheliumwithinfluenzaparticle+K288*IL6*EpitheliumLung+K288*IL6*ResistantEpithelium
dEpiKilledbyTc=(K34*Epitheliumwithreplicatedinfluenza*K40*lag12_TcLymphnode)+(K34*Epitheliumwithinfluenzaparticle*K40*lag12_TcLymphnode)
dEpiKilledbyVirus=K11*FreeInfluenza*EpitheliumLung
dTnaive=K322*(1E5-Tnaive)-K3222*FreeInfluenza*Tnaive
dIgM=(K400*8*2*TcLymphnode-K401*IgM)
dIgG=(K500*8*2*TcLymphnode-K501*IgG)
dCR=(-Kp14*CR+Kp41*CRP)+(-KpC*CR)+KCon/2
dCRP=-((-Kp14*CR+Kp41*CRP))
dKCon=0
dC_intracellularRDV_total=(CL_percell*(C_extracellularRDV_total*F_extracellular)/V_percell)-(CL_percell*(C_intracellularRDV_total*F_intracellular)/V_percell)-(Km*(C_intracellularRDV_total*F_intracellular))-Knew*C_intracellularRDV_total
dC_extracellularRDV_total=(((-Kp14*CR+Kp41*CRP)-KpC*CR+KCon/2)/V1)*1000/1000000000/603
dcell_number=Kcell*cell_number
dTP=(Km*(C_intracellularRDV_total*F_intracellular))-Kc*TP
    return(list(c(dEpitheliumwithreplicatedinfluenza,dFreeInfluenza,dEpitheliumwithinfluenzaparticle,dEpitheliumLung,dInfectedAPC,dIL6,dResistantEpithelium,dIFNA1,dTcLymphnode,dActivatedAPCLymphnode,dA,dEpiKilledbyIFN,dEpiKilledbyIL6,dEpiKilledbyTc,dEpiKilledbyVirus,dTnaive,dIgG,dIgM,dCR,dCRP,dKCon,dC_intracellularRDV_total,dC_extracellularRDV_total,dcell_number,dTP)))
})}